#!/usr/bin/env node

import { readFileSync } from "node:fs";
import { relative } from "node:path";
import { execFileSync } from "node:child_process";

const forbidden = [
  { name: "em dash", pattern: /\u2014/u },
  { name: "en dash", pattern: /\u2013/u },
  { name: "AI attribution", pattern: /(?:generated by|co-authored-by|created by)\s+(?:ai|chatgpt|codex|openai|claude)/iu }
];

const emojiPattern = /\p{Emoji_Presentation}|\p{Extended_Pictographic}/u;
const tracked = execFileSync("git", ["ls-files"], { encoding: "utf8" })
  .split("\n")
  .filter(Boolean)
  .filter((file) => !file.startsWith("node_modules/"))
  .filter((file) => !file.endsWith("package-lock.json"));

// Captured model responses and their quoted review evidence must stay verbatim.
// Continue checking authored evaluation scripts and README documentation.
const recordedEvaluation = /^evaluations\/mentor-100\/(?:(?:runs|baselines|skill-rechecks|smoke-failures)\/|manual-[^/]+\.json$|paired-baselines\.json$|review\.html$)/u;

const automaticTranscript = /^evaluations\/automatic-0\.1\/(?:(?:claude-installed|codex-installed)\/\d+\/(?:events\.jsonl|response\.md|mcp-inspection\.txt|stderr\.txt|result\.json)|(?:codex-hooks-only|codex-untrusted|copilot|gemini)\/result\.json)$/u;

const failures = [];

for (const file of tracked) {
  if (recordedEvaluation.test(file) || automaticTranscript.test(file) || /^evaluations\/next-build\/(?!README\.md$|cases\.json$|summary\.json$)/u.test(file)) continue;
  const contents = readFileSync(file);
  if (contents.includes(0)) {
    continue;
  }

  const text = contents.toString("utf8");
  for (const rule of forbidden) {
    if (rule.pattern.test(text)) {
      failures.push(`${relative(process.cwd(), file)} contains ${rule.name}`);
    }
  }

  if (emojiPattern.test(text)) {
    failures.push(`${relative(process.cwd(), file)} contains emoji-like Unicode`);
  }
}

if (failures.length > 0) {
  for (const failure of failures) {
    console.error(failure);
  }
  process.exit(1);
}
