#!/usr/bin/env python3
"""Render the completed, evidence-linked local field review without external assets."""
import html,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=Path.home()/'Downloads/Greybeard-review'
EVAL=ROOT/'evaluations/mentor-100'
def esc(s): return html.escape(str(s))
cases=json.loads((EVAL/'cases.json').read_text())
reviews=[]
for path in sorted(EVAL.glob('manual-review-*.json')):
    data=json.loads(path.read_text());reviews.extend(data if isinstance(data,list) else data['reviews'])
by_id={str(r['id']).zfill(3):r for r in reviews}
assert len(cases)==100 and len(by_id)==100,'Require all100 completed substantive reviews'
rows=[];usage={'input_tokens':0,'cached_input_tokens':0,'output_tokens':0};verdicts={}
for case in cases:
    id=case['id'];result=json.loads((EVAL/'runs'/id/'result.json').read_text());review=by_id[id]
    assert result['exitCode']==0 and result['response'],'Require actual completed responses'
    for entry in result.get('usage',[]):
        for name in usage: usage[name]+=entry.get(name,0)
    verdict=review['verdict'];verdicts[verdict]=verdicts.get(verdict,0)+1
    rows.append(f'''<details class="case" data-search="{esc(case['category']+' '+verdict+' '+case['prompt'])}"><summary><span class="id">{id}</span><span>{esc(case['prompt'])}</span><span class="tag">{esc(verdict)}</span></summary><div class="casebody"><p class="eyebrow">{esc(case['category'])} · {esc(review['valueAdded'])}</p><h3>Review</h3><p>{esc(review['rationale'])}</p><p class="note">Expected: {esc(case['expected'])}</p><h3>Actual response</h3><pre>{esc(result['response'])}</pre><p><a href="evaluation/runs/{id}/result.json">Response, tool evidence, and usage</a></p></div></details>''')
OUT.mkdir(parents=True,exist_ok=True)
shutil.copytree(EVAL,OUT/'evaluation',dirs_exist_ok=True,ignore=shutil.ignore_patterns('events.jsonl','stderr.txt','__pycache__'))
for name in ['field-review.md','issues-and-next-build.md','tenant-observations.md']:
    (OUT/name).write_text((ROOT/'docs/0.1/reviews'/name).read_text().replace('../../../evaluations/mentor-100/', 'evaluation/'))
counts=' · '.join(f'{n} {k}' for k,n in sorted(verdicts.items()))
body=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Greybeard · Field review</title>
<style>:root{{color-scheme:light;--ink:#25382f;--muted:#5b665c;--line:#cdd3c8;--paper:#f6f4ec}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 system-ui,sans-serif}}main{{max-width:1080px;margin:auto;padding:42px 24px 80px}}h1,h2{{font-family:Georgia,serif;line-height:1.12}}h1{{font-size:clamp(36px,6vw,66px);max-width:820px}}h2{{font-size:32px;margin-top:48px}}h3{{font-size:18px}}a{{color:#245a43}}.eyebrow{{font:700 12px system-ui;letter-spacing:.12em;text-transform:uppercase;color:var(--muted)}}.lede{{font-size:22px;max-width:850px}}.cards{{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:28px 0}}.card,.panel{{background:#fff;border:1px solid var(--line);border-radius:10px;padding:22px}}.big{{font-size:38px;font-weight:650;display:block}}.note{{color:var(--muted);font-size:14px}}li{{margin:10px 0}}.case{{border:1px solid var(--line);border-radius:8px;margin:10px 0;background:#fff}}summary{{display:flex;align-items:center;gap:16px;padding:16px;cursor:pointer}}.id{{font-variant-numeric:tabular-nums;color:var(--muted)}}.tag{{margin-left:auto;font-size:12px;padding:4px 10px;border-radius:18px;background:#e9eee6;white-space:nowrap}}.casebody{{padding:0 24px 20px;border-top:1px solid var(--line)}}pre{{white-space:pre-wrap;overflow-wrap:anywhere;font:15px/1.6 system-ui}}input{{width:100%;padding:14px;border:1px solid var(--line);border-radius:8px;font:inherit}}:focus-visible{{outline:3px solid #8fae79;outline-offset:3px}}@media(max-width:600px){{.cards{{grid-template-columns:1fr}}summary{{gap:8px;font-size:14px}}main{{padding:24px 16px}}}}</style>
<main><p class="eyebrow">Greybeard 0.1 · Field review · 11 September 2026</p><h1>Would an admin miss Greybeard?</h1><p class="lede">The strongest reason to keep it is a remembered rule, correction, or exception that changes the next decision. A generic checklist does not establish that advantage.</p>
<div class="cards"><div class="card"><span class="big">100</span>Distinct prompts, actual Codex responses, and substantive reviews</div><div class="card"><span class="big">180</span>Passing local source tests, plus executable and browser verification</div><div class="card"><span class="big">19</span>Read-only beta Graph probes through Lokka, with observed errors retained</div></div>
<section class="panel"><h2 style="margin-top:0">What changed</h2><ul><li>Oversized recall budgets are capped without an avoidable validation retry.</li><li>Recall identifies byte accounting explicitly and returns compact memory nodes.</li><li>Pause suppresses recalled advice; linked lessons preserve their original source.</li><li>Preferences and lessons have separate review groups and visible memory IDs.</li><li>Skills explain when a confirmed memory changes advice, without claiming a separate assessment.</li></ul><p class="note">These source improvements are not silently installed into the existing published0.1 download.</p></section>
<h2>What the environment changed</h2><p>The lab has multiple Windows compliance policies with different assignment states, old device check-ins, and a report-only Conditional Access policy. A useful mentor resolves the actual target and asks for fresh evaluation evidence. It does not invent a remembered reason or assume current access is blocked.</p><p>Production organization read returned403; a limited application read worked. Production-wide context remains unverified. No tenant changes or memory confirmations were made.</p><p><a href="tenant-observations.md">Read the scoped tenant observations and API errors</a> · <a href="private/tenant-evidence.json">Private local raw evidence</a></p>
<h2>What to build next</h2><ol><li>Prove relevant recall during normal client use without a forced memory instruction.</li><li>Improve relevance, especially paraphrases, exceptions, and generic preferences.</li><li>Keep confirmed rules separate from dated observations and unverified explanations.</li><li>Measure useful changes to advice against no-Greybeard baselines and added context.</li><li>Make learning from outcomes easier while preserving explicit confirmation.</li></ol><p><a href="issues-and-next-build.md">Full issue list, priorities, and acceptance criteria</a> · <a href="evaluation/review.html">Evaluation summary and baseline comparison</a></p>
<p><a href="field-review.md">Full findings, measured usage, and supplementary skill checks</a></p><h2>Read the100 reviews</h2><p>{esc(counts)}. These are editorial judgments, not a statistical safety certification.</p><p class="note">Method:100 independent Codex conversations using isolated synthetic memories and forced recall; no natural skill-discovery claim. Anonymized lab snapshots were supplied to five cases. The model did not perform live tenant reads. Raw measured aggregate host usage: {usage['input_tokens']:,} input tokens, including {usage['cached_input_tokens']:,} cached input tokens, and {usage['output_tokens']:,} output tokens. This includes host context and tool round trips, not just Greybeard memory. It is not a monetary cost estimate.</p><label for="search">Filter by prompt, category, or verdict</label><input id="search" type="search" placeholder="Try correction, pause, concern, or compliance"><p id="count" class="note">100 prompts shown</p>{''.join(rows)}</main><script>document.getElementById('search').addEventListener('input',e=>{{let n=0;const q=e.target.value.toLowerCase();document.querySelectorAll('.case').forEach(x=>{{x.hidden=!x.dataset.search.toLowerCase().includes(q);if(!x.hidden)n++}});document.getElementById('count').textContent=n+' prompts shown'}})</script></html>'''
body=body.replace('published0.1','published 0.1').replace('returned403','returned 403').replace('the100','the 100').replace('Method:100','Method: 100')
(OUT/'index.html').write_text(body)
print(OUT/'index.html');print(counts)
