/** A local, dependency-free perspective view of recorded memory relationships. */
export const memoryMapStyles = `
.map-heading{display:flex;justify-content:space-between;align-items:start;gap:24px}.map-heading{margin-top:24px}.map-heading h1{margin:10px 0 12px}.map-heading .lead{margin-bottom:0}.map-controls{display:flex;gap:12px;flex-wrap:wrap;align-items:end;margin:16px 0 12px}.map-controls label{margin:0;display:grid;gap:7px;font-size:13px;color:var(--muted)}.map-controls input,.map-controls select{max-width:220px}.map-layout{display:grid;grid-template-columns:minmax(0,1.8fr) minmax(260px,1fr);gap:20px;align-items:start}.map-stage{position:relative;border-radius:18px;background:#142b23;color:#f5f3e8;overflow:hidden;border:1px solid #345746}.map-stage svg{display:block;width:100%;height:auto;min-height:340px;touch-action:none;cursor:grab;outline-offset:-5px}.map-stage svg:active{cursor:grabbing}.map-stage svg:focus-visible{outline:3px solid #d8ad76}.map-stage-head{display:flex;justify-content:space-between;padding:22px 24px 0;gap:12px;font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:#c8d9c9}.map-stage-foot{padding:0 24px 22px;color:#bacbbc;font-size:13px}.map-stage .map-empty{padding:70px 30px;text-align:center}.map-timeline{padding:18px 24px;border-top:1px solid #345746;display:grid;gap:9px}.map-timeline input{width:100%;accent-color:#d8ad76}.map-timeline label{display:flex;justify-content:space-between;gap:16px;font-size:13px;color:#d7e3d7}.map-legend{display:flex;flex-wrap:wrap;gap:18px;font-size:12px;color:var(--muted);margin:14px 0 24px}.map-legend span:before{content:'';display:inline-block;width:9px;height:9px;border-radius:50%;background:#315945;margin-right:7px}.map-legend .proposed:before{background:transparent;border:1px dashed #a26c32}.map-legend .archived:before{background:#929a93}.map-legend .source:before{background:#c18e51}.map-detail{padding:24px;min-height:320px}.map-detail h2{font-size:25px;margin:10px 0}.map-detail .map-exact{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.6}.map-detail dl{display:grid;grid-template-columns:auto 1fr;gap:9px 16px;font-size:13px}.map-detail dt{color:var(--muted)}.map-detail dd{margin:0;overflow-wrap:anywhere}.map-detail .map-links{display:grid;gap:8px;margin-top:16px}.map-detail .map-links button{text-align:left;font-size:13px;padding:10px}.map-index{margin-top:20px;padding:20px}.map-index label{display:block;margin-bottom:10px}.map-index select{width:100%;max-width:none;min-height:165px;white-space:normal}.map-index option{padding:8px}.map-flat .map-layout{grid-template-columns:1fr 1fr}.map-flat .map-stage svg,.map-flat .map-stage-head,.map-flat .map-stage-foot{display:none}.map-flat .map-stage{background:#eef0e7;color:var(--ink)}.map-flat .map-timeline label{color:var(--ink)}.map-flat .map-timeline{border-color:var(--line)}.map-flat .map-index{margin-top:0}.map-note{max-width:75ch}.map-small-actions{display:flex;gap:8px;flex-wrap:wrap}.map-small-actions button{font-size:12px;padding:10px 13px}#map-feedback{min-height:1.5em}#map-title{font-size:clamp(35px,4vw,55px)}
@media(max-width:1050px){.map-layout,.map-flat .map-layout{grid-template-columns:1fr}.map-heading{display:block}.map-stage svg{min-height:250px}.map-detail{min-height:0}}
`;

export const memoryMapMarkup = `
<section class="view" id="view-map" hidden>
<div class="map-heading"><div><div class="eyebrow">EXPERIENCE, CONNECTED</div><h1 id="map-title">Your memory, in perspective.</h1><p class="lead map-note">Explore where lessons came from, when they were saved, and how they connect.</p></div><button id="map-refresh">Refresh map</button></div>
<div class="map-controls"><label>Find a memory<input id="map-query" type="search" placeholder="Search remembered text"></label><label>Saved from<select id="map-source"><option value="">Every source</option></select></label><label>Status<select id="map-status"><option value="">Every status</option><option value="confirmed">Confirmed</option><option value="candidate">Needs review</option><option value="superseded">Superseded</option></select></label><label>Show up to<select id="map-limit"><option value="200">200 memories</option><option value="500">500 memories</option><option value="1000">1,000 memories</option></select></label></div>
<p id="map-feedback" class="note" role="status" aria-live="polite">Open the map to load this profile's local memories.</p>
<div class="map-layout"><div><div class="map-stage"><div class="map-stage-head"><span>LOCAL MEMORY ATLAS</span><span id="map-count">0 memories</span></div><svg id="memory-globe" viewBox="0 0 1000 640" tabindex="0" role="img" aria-label="Rotatable memory globe. Drag or use arrow keys to rotate. Select a memory using the list below for keyboard access."><title>Recorded memory connections</title></svg><div id="map-empty" class="map-empty" hidden>No memories match this view.</div><div class="map-stage-foot">Drag to rotate · Arrow keys to turn · Click a memory to inspect</div><div class="map-timeline"><label for="map-time"><span>Saved through</span><output id="map-time-label">All time</output></label><input id="map-time" type="range" min="0" max="100" value="100" step="1" aria-label="Show memories saved through this point in time"></div></div>
<div class="map-legend"><span>Confirmed</span><span class="proposed">Needs review</span><span class="archived">Superseded</span><span class="source">Recorded source</span></div>
<div class="map-small-actions"><button id="map-reset">Reset view</button><button id="map-flat" aria-pressed="false">Flat view</button><button id="map-lines" aria-pressed="true">Show source connections</button></div>
<div class="panel map-index"><label for="map-select">Select a memory <small>· newest first</small></label><select id="map-select" size="7" aria-label="Memories in the map"></select></div></div>
<div id="map-detail" class="panel map-detail" aria-label="Selected memory"><div class="eyebrow">THE STORY BEHIND A LESSON</div><h2>Select a memory.</h2><p class="note">Its exact text, recorded source, timestamps and connections will appear here.</p></div></div>
<p class="foot map-note">Solid connections are stored relationships or corrections. Dashed connections show the recorded source. Position and distance are visual layout only, not geography or evidence of similarity. Some older memories do not record which AI tool saved them. This map runs locally and makes no model calls.</p>
</section>`;

export const memoryMapScript = String.raw`
let mapData=null,mapSelected=null,mapYaw=.3,mapPitch=-.2,mapFlat=false,mapSources=true,mapLoading=0,mapSearchTimer,mapFrame=0,mapDrag=null,mapPositions=new Map();
const mapSvgNS='http://www.w3.org/2000/svg';
function mapSourceName(source){const names={'automatic-claude':'Claude Code / Desktop Code','automatic-codex':'Codex','automatic-cursor':'Cursor','automatic-gemini':'Gemini','automatic-copilot':'Copilot','local-ui':'Companion','local-cli':'Terminal','mcp-agent':'AI tool · host not recorded'};return names[source]||source||'Source not recorded';}
function mapDate(value){return value!==null&&value!==undefined?new Date(value*1000).toLocaleString():'Not recorded';}
function mapStatus(node){return node.supersededAt!==null?'Superseded':node.status==='candidate'?'Needs review':'Confirmed';}
function mapSvg(tag,attrs={},text){const element=document.createElementNS(mapSvgNS,tag);for(const [key,value]of Object.entries(attrs))element.setAttribute(key,String(value));if(text!==undefined)element.textContent=text;return element;}
async function loadMemoryMap(){const generation=++mapLoading;$('map-feedback').textContent='Loading local memories…';try{const data=await api('/memory-map',{query:$('map-query').value,source:$('map-source').value,status:$('map-status').value,limit:Number($('map-limit').value)});if(generation!==mapLoading)return;mapData=data;const selectedSource=$('map-source').value;$('map-source').replaceChildren();const all=el('option','Every source');all.value='';$('map-source').append(all);for(const source of data.sources){const option=el('option',mapSourceName(source));option.value=source;$('map-source').append(option);}$('map-source').value=selectedSource;$('map-feedback').textContent='Showing '+data.nodes.length+' of '+data.matched+' matching memories'+(data.nodes.length<data.matched?' · narrow the search or increase the limit':'')+'. Updated '+new Date().toLocaleTimeString()+'.';if(!data.nodes.some(n=>n.id===mapSelected))mapSelected=data.nodes[0]?.id??null;mapUpdate();}catch(error){if(generation===mapLoading){mapData=null;mapSelected=null;mapUpdate();$('map-feedback').textContent='Could not load this memory map. '+error.message;}}}
function mapVisible(){if(!mapData)return [];const value=Number($('map-time').value);const earliest=mapData.earliest||0,latest=mapData.latest||earliest;const cutoff=value===100?Infinity:earliest+(latest-earliest)*value/100;$('map-time-label').textContent=value===100?'All time':mapDate(cutoff);return mapData.nodes.filter(n=>n.createdAt<=cutoff);}
function mapUpdate(){const nodes=mapVisible();$('map-count').textContent=nodes.length+' memories';$('map-empty').hidden=nodes.length>0;$('map-time').disabled=!mapData?.nodes.length||mapData.earliest===mapData.latest;$('map-select').replaceChildren();for(const node of nodes){const option=el('option','#'+node.id+' · '+mapStatus(node)+' · '+node.content.slice(0,110));option.value=String(node.id);$('map-select').append(option);}if(!nodes.some(n=>n.id===mapSelected))mapSelected=nodes[0]?.id??null;$('map-select').value=mapSelected===null?'':String(mapSelected);mapDetails();mapDraw();}
function mapProject(point){const cy=Math.cos(mapYaw),sy=Math.sin(mapYaw),cp=Math.cos(mapPitch),sp=Math.sin(mapPitch);const x=point[0]*cy+point[2]*sy,z=-point[0]*sy+point[2]*cy;const y=point[1]*cp-z*sp,depth=point[1]*sp+z*cp;const scale=820/(820-depth*210);return {x:500+x*235*scale,y:315+y*235*scale,z:depth,scale};}
function mapPath(points){return points.map((p,i)=>{const q=mapProject(p);return(i?'L':'M')+q.x.toFixed(1)+','+q.y.toFixed(1);}).join(' ');}
function mapDraw(){if($('view-map').hidden)return;const svg=$('memory-globe');svg.replaceChildren(mapSvg('title',{},'Recorded memory connections'));mapPositions=new Map();const nodes=mapVisible();if(!nodes.length)return;
const grid=mapSvg('g',{fill:'none',stroke:'#466453','stroke-width':.65,opacity:.42});for(const latitude of [-.65,0,.65]){const radius=Math.sqrt(1-latitude*latitude),points=[];for(let i=0;i<=80;i++){const a=i/80*Math.PI*2;points.push([Math.cos(a)*radius,latitude,Math.sin(a)*radius]);}grid.append(mapSvg('path',{d:mapPath(points)}));}for(let meridian=0;meridian<4;meridian++){const points=[];for(let i=0;i<=80;i++){const a=i/80*Math.PI*2,b=meridian*Math.PI/4;points.push([Math.cos(a)*Math.cos(b),Math.sin(a),Math.cos(a)*Math.sin(b)]);}grid.append(mapSvg('path',{d:mapPath(points)}));}svg.append(grid);
const sorted=[...nodes].sort((a,b)=>a.source.localeCompare(b.source)||a.createdAt-b.createdAt||a.id-b.id);const sourcePoints=new Map();for(let i=0;i<sorted.length;i++){const node=sorted[i],y=sorted.length===1?0:1-2*(i+.5)/sorted.length,angle=i*Math.PI*(3-Math.sqrt(5)),r=Math.sqrt(1-y*y);const point=[Math.cos(angle)*r,y,Math.sin(angle)*r];mapPositions.set(node.id,{...mapProject(point),node,point});if(!sourcePoints.has(node.source))sourcePoints.set(node.source,[]);sourcePoints.get(node.source).push(point);}
const groups=[...sourcePoints.keys()].sort();const hubs=new Map(groups.map((source,i)=>{const angle=i/groups.length*Math.PI*2;return[source,{x:500+Math.cos(angle)*395,y:315+Math.sin(angle)*268}];}));
const lines=mapSvg('g',{'pointer-events':'none'});if(mapSources)for(const p of mapPositions.values()){const hub=hubs.get(p.node.source);lines.append(mapSvg('line',{x1:p.x,y1:p.y,x2:hub.x,y2:hub.y,stroke:'#d1ab72','stroke-dasharray':'3 6','stroke-width':.7,opacity:p.node.id===mapSelected ? .5 : .10}));}
for(const edge of mapData.edges){const a=mapPositions.get(edge.source),b=mapPositions.get(edge.target);if(!a||!b)continue;const selected=edge.source===mapSelected||edge.target===mapSelected;lines.append(mapSvg('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:edge.kind==='correction'?'#e6b975':'#a8d7ba','stroke-width':selected?2:1,opacity:selected ? .95 : .38}));}svg.append(lines);
for(const [source,hub]of hubs){const g=mapSvg('g',{'pointer-events':'none'});g.append(mapSvg('circle',{cx:hub.x,cy:hub.y,r:5,fill:'#d8ad76'}));const label=mapSourceName(source);g.append(mapSvg('text',{x:hub.x,y:hub.y+(hub.y<315?-15:23),'text-anchor':hub.x>650?'end':hub.x<350?'start':'middle',fill:'#dec59e','font-size':20},label.length>27?label.slice(0,26)+'…':label));svg.append(g);}
for(const p of [...mapPositions.values()].sort((a,b)=>a.z-b.z)){const selected=p.node.id===mapSelected,archived=p.node.supersededAt!==null,candidate=p.node.status==='candidate';const radius=(selected?8:5)*p.scale;const g=mapSvg('g',{'data-memory-id':p.node.id});g.append(mapSvg('title',{},'#'+p.node.id+' · '+mapStatus(p.node)+' · '+p.node.content.slice(0,140)));if(selected)g.append(mapSvg('circle',{cx:p.x,cy:p.y,r:radius+5,fill:'none',stroke:'#f7e1b7','stroke-width':1,opacity:.8}));g.append(mapSvg('circle',{cx:p.x,cy:p.y,r:radius,fill:archived?'#8a998e':candidate?'#213b2c':'#bbd6bd',stroke:selected?'#fff0d5':candidate?'#d8ad76':'#e4f0df','stroke-width':selected?2:1,'stroke-dasharray':candidate?'2 2':'none',opacity:archived ? .45 : .50+(p.z+1)*.25}));svg.append(g);}}
function mapSchedule(){if(!mapFrame)mapFrame=requestAnimationFrame(()=>{mapFrame=0;mapDraw();});}
function mapDetails(){const panel=$('map-detail');panel.replaceChildren();const node=mapData?.nodes.find(n=>n.id===mapSelected);if(!node){panel.append(el('div','THE STORY BEHIND A LESSON','eyebrow'),el('h2','Select a memory.'),el('p','Use the globe or memory list to explore its exact text and recorded relationships.','note'));return;}panel.append(el('div',mapStatus(node)+' · #'+node.id,'eyebrow'),el('h2',mapSourceName(node.source)),el('p',node.content,'map-exact'));const dl=el('dl');for(const [label,value]of [['Saved',mapDate(node.createdAt)],['Confirmed',mapDate(node.confirmedAt)],['Last used',mapDate(node.lastUsedAt)],['Observed',mapDate(node.observedAt)],['Type',node.type],['Scope',node.scope],['Recorded source',node.source||'Not recorded'],['Storage','This computer · '+(mapData.tenant==='local'?'local memory':'selected tenant profile')]])dl.append(el('dt',label),el('dd',value));panel.append(dl);if(node.outcome)panel.append(el('p','Reported outcome: '+node.outcome,'note'));const visibleIds=new Set(mapVisible().map(n=>n.id));const related=mapData.edges.filter(edge=>visibleIds.has(edge.source)&&visibleIds.has(edge.target)&&(edge.source===node.id||edge.target===node.id));const links=el('div',undefined,'map-links');links.append(el('strong','Recorded connections'));if(!related.length)links.append(el('p','No connected memories are included in this view.','note'));for(const edge of related){const other=edge.source===node.id?edge.target:edge.source;const correction=mapData.nodes.find(n=>n.id===edge.source);const label=edge.relation==='corrects'?(correction?.status==='candidate'?(edge.source===node.id?'Proposed correction to':'Proposed replacement'):(edge.source===node.id?'Corrects':'Corrected by')):edge.relation.replaceAll('_',' ')+(edge.source===node.id?' →':' ←');links.append(button(label+' #'+other,()=>{mapSelected=other;mapUpdate();}));}panel.append(links,button('Open in Your memory',()=>{$('search').value=node.content;$('type-filter').value='';$('status-filter').value='';$('scope-filter').value='';view('memory');}));}
$('map-refresh').onclick=()=>void loadMemoryMap();$('map-query').oninput=()=>{clearTimeout(mapSearchTimer);mapSearchTimer=setTimeout(()=>void loadMemoryMap(),250);};for(const id of ['map-source','map-status','map-limit'])$(id).onchange=()=>void loadMemoryMap();$('map-time').oninput=mapUpdate;$('map-select').onchange=()=>{mapSelected=Number($('map-select').value);mapDetails();mapSchedule();};$('map-reset').onclick=()=>{mapYaw=.3;mapPitch=-.2;$('map-time').value='100';mapUpdate();};$('map-flat').onclick=()=>{mapFlat=!mapFlat;$('view-map').classList.toggle('map-flat',mapFlat);$('map-flat').setAttribute('aria-pressed',String(mapFlat));$('map-flat').textContent=mapFlat?'Globe view':'Flat view';};$('map-lines').onclick=()=>{mapSources=!mapSources;$('map-lines').setAttribute('aria-pressed',String(mapSources));mapSchedule();};
$('memory-globe').onpointerdown=event=>{if(event.button!==0)return;mapDrag={x:event.clientX,y:event.clientY,lastX:event.clientX,lastY:event.clientY,moved:false};$('memory-globe').setPointerCapture(event.pointerId);};$('memory-globe').onpointermove=event=>{if(!mapDrag)return;const dx=event.clientX-mapDrag.lastX,dy=event.clientY-mapDrag.lastY;mapDrag.moved=mapDrag.moved||Math.hypot(event.clientX-mapDrag.x,event.clientY-mapDrag.y)>4;if(mapDrag.moved){mapYaw+=dx*.008;mapPitch=Math.max(-1.4,Math.min(1.4,mapPitch+dy*.008));mapSchedule();}mapDrag.lastX=event.clientX;mapDrag.lastY=event.clientY;};$('memory-globe').onpointerup=event=>{if(!mapDrag)return;if(!mapDrag.moved){const matrix=$('memory-globe').getScreenCTM();if(matrix){const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());const candidates=[...mapPositions.values()].filter(p=>Math.hypot(p.x-point.x,p.y-point.y)<14).sort((a,b)=>b.z-a.z);if(candidates.length){mapSelected=candidates[0].node.id;$('map-select').value=String(mapSelected);mapDetails();mapSchedule();}}}mapDrag=null;};$('memory-globe').onpointercancel=()=>{mapDrag=null;};$('memory-globe').onkeydown=event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(event.key))return;event.preventDefault();if(event.key==='Home'){mapYaw=.3;mapPitch=-.2;}else if(event.key==='ArrowLeft')mapYaw-=.15;else if(event.key==='ArrowRight')mapYaw+=.15;else mapPitch=Math.max(-1.4,Math.min(1.4,mapPitch+(event.key==='ArrowUp'?-.15:.15)));mapSchedule();};
`;
